### ISSUE TITLE
3 possible errors detected, but only 2 shown

### ISSUE THREAD

**Issue by pdehaan** [CenturyLinkLabs/lorry-ui#178]
### Steps to reproduce:
1. Go to lorry.io and validate your YAML file via direct input
2. Paste the following:
  ```yaml
db:
  image: postgres:9.3
frontend_watcher:
  extends:
    file: docker-compose-base.yml
    service: frontend-watcher
server:
  extends:
    file: docker-compose-base.yml
    service: server
  links:
    - db
    - frontend_watcher
```

3. Verify.

### Actual results:
> 3 possible errors were detected.

But only 2 errors are displayed. I'm assuming I have 2 errors on the same line (line 3).
