### ISSUE TITLE
Invalid service name. Valid characters are [a-zA-Z0-9]

### ISSUE THREAD

**Issue by pdehaan** [CenturyLinkLabs/lorry-ui#179]
### Steps to reproduce:
Try and validate the following YAML business:
```yaml
db:
    image: postgres:9.3

frontend_watcher:
    extends:
        file: docker-compose-base.yml
        service: frontend-watcher

server:
    extends:
        file: docker-compose-base.yml
        service: server
    links:
        - db
        - frontend_watcher
```

### Actual results:

> _"Invalid service name. Valid characters are [a-zA-Z0-9]"_

### Expected results:
It should probably allow hyphens and underscores. I haven't been able to find an official spec on container naming yet, but this is the closest I've gotten:

[**docker/compose** ./compose/config/validation.py:40](https://github.com/docker/compose/blob/e35bf47a7f77c3299b8ce4405390f944fc57e8c4/compose/config/validation.py#L40):
```py
VALID_NAME_CHARS = '[a-zA-Z0-9\._\-]'
```
